### ISSUE TITLE
Add ability to pass a list of buckets to create

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-cos#239]
### Description

Allow to pass a list of buckets as input - loop within the module on creating that list.
Should work with creating a cos instance, or pointing to existing cos instance

### New or affected modules

- [terraform-ibm-cos](https://github.com/terraform-ibm-modules/terraform-ibm-cos)

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by shemau** [comment]
🎉 This PR is included in version 6.10.0 🎉

See release notes.

Rather than pass a list of buckets to the existing module, a new sub module is created that takes a list of buckets and calls the root module as required to create them. The root module retains the existing functionality for easy of adoption and to avoid significant migration changes.
